CREATE SEQUENCE SQ_T_BTTF_ACONTECIMENTO
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 999
    MINVALUE 1
    NOCYCLE
    CACHE 5;
    
CREATE SEQUENCE SQ_T_BTTF_CONSEQUENCIA
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 999
    MINVALUE 1
    NOCYCLE
    CACHE 5;
    
CREATE SEQUENCE SQ_T_BTTF_PERSONAGEM
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 999
    MINVALUE 1
    NOCYCLE
    CACHE 5;

CREATE SEQUENCE SQ_T_BTTF_PERSONAGEM_ACONT
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999999999
    MINVALUE 1
    NOCYCLE
    CACHE 5;
    
    
    
